resolver: lts-12.14

packages:
- .

docker:
  enable: false
  image: ocramz/cmbnt-test-dev

extra-deps:
- rigel-viz-0.2.0.0
- lucid-extras-0.2.2
- aeson-1.4.2.0
- containers-0.6.0.1

# flags: {}

# extra-package-dbs: []

# Use the GHC we find on the path
system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=1.9"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
